---
- name: this playbook is to install packages 
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum: 
      name: ['tree', 'git', 'make', 'gcc', 'wget', 'telnet', 'gzip']
      state: installed

