---
- name: this playbook is to install httpd and start httpd services 
  hosts: webservers
  become: true
  tasks:
  - name: install package
    yum: 
      name: httpd 
      state: installed
    notify: start apache

  handlers:
  - name: start apache 
    service: 
      name: httpd
      enabled: yes
      state: restarted

